#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
source "$SCRIPT_DIR/colors.sh"

ALACRITTY_OUT="$HOME/.config/alacritty/glitchberry.toml"
VIM_OUT="$HOME/.vim/colors/glitchberry.vim"
TMUX_OUT="$SCRIPT_DIR/tmux-theme.conf"

echo "Generating Glitchberry theme..."

# ---------- Alacritty ----------
cat > "$ALACRITTY_OUT" << EOF
# Glitchberry — Dark  [generated by ~/.config/theme/generate.sh]
# Deep space jewel tones with glowing pastel accents

[colors.primary]
background = "$THEME_BG"
foreground = "$THEME_FG"
dim_foreground = "$THEME_MUTED"
bright_foreground = "$THEME_FG_BRIGHT"

[colors.cursor]
cursor = "$THEME_AMBER"
text = "$THEME_BG_ALT"

[colors.vi_mode_cursor]
cursor = "$THEME_PURPLE"
text = "$THEME_BG_ALT"

[colors.selection]
background = "$THEME_SELECTION"
text = "CellForeground"

[colors.search.matches]
background = "$THEME_SEARCH"
foreground = "$THEME_CYAN"

[colors.search.focused_match]
background = "$THEME_CYAN"
foreground = "$THEME_BG_ALT"

[colors.footer_bar]
foreground = "$THEME_BG_ALT"
background = "$THEME_MUTED"

[colors.hints.start]
foreground = "$THEME_BG_ALT"
background = "$THEME_AMBER"

[colors.hints.end]
foreground = "$THEME_BG_ALT"
background = "$THEME_MUTED"

[colors.normal]
black   = "$THEME_BORDER"
red     = "$THEME_RED"
green   = "$THEME_GREEN"
yellow  = "$THEME_AMBER"
blue    = "$THEME_PURPLE"
magenta = "$THEME_MAGENTA"
cyan    = "$THEME_CYAN"
white   = "$THEME_FG"

[colors.bright]
black   = "$THEME_COMMENT"
red     = "$THEME_RED_BRIGHT"
green   = "$THEME_GREEN_BRIGHT"
yellow  = "$THEME_AMBER_BRIGHT"
blue    = "$THEME_PURPLE_BRIGHT"
magenta = "$THEME_MAGENTA_BRIGHT"
cyan    = "$THEME_CYAN_BRIGHT"
white   = "$THEME_FG_BRIGHT"

[colors.dim]
black   = "$THEME_APP"
red     = "$THEME_RED_DIM"
green   = "$THEME_GREEN_DIM"
yellow  = "$THEME_AMBER_DIM"
blue    = "$THEME_PURPLE_DIM"
magenta = "$THEME_MAGENTA_DIM"
cyan    = "$THEME_CYAN_DIM"
white   = "$THEME_MUTED"
EOF
echo "  -> $ALACRITTY_OUT"

# ---------- Vim ----------
cat > "$VIM_OUT" << 'VIMEOF'
" glitchberry.vim — deep space jewel tones
" Generated by ~/.config/theme/generate.sh — do not edit by hand
" Maintainer: deepak
" License: MIT

set background=dark
highlight clear
if exists('syntax_on')
  syntax reset
endif
let g:colors_name = 'glitchberry'

VIMEOF

# Write palette variables (these get expanded)
cat >> "$VIM_OUT" << EOF
" --- Palette ---
let s:bg          = '$THEME_BG'
let s:bg_alt      = '$THEME_BG_ALT'
let s:sidebar     = '$THEME_SIDEBAR'
let s:app         = '$THEME_APP'
let s:cursorline  = '$THEME_CURSORLINE'
let s:selection   = '$THEME_SELECTION'
let s:search      = '$THEME_SEARCH'

let s:fg          = '$THEME_FG'
let s:fg_bright   = '$THEME_FG_BRIGHT'
let s:fg_func     = '$THEME_FG_FUNCTION'
let s:muted       = '$THEME_MUTED'
let s:comment     = '$THEME_COMMENT'
let s:border      = '$THEME_BORDER'
let s:subtle      = '$THEME_SUBTLE'

let s:red         = '$THEME_RED'
let s:green       = '$THEME_GREEN'
let s:amber       = '$THEME_AMBER'
let s:purple      = '$THEME_PURPLE'
let s:magenta     = '$THEME_MAGENTA'
let s:cyan        = '$THEME_CYAN'

let s:red_bright    = '$THEME_RED_BRIGHT'
let s:green_bright  = '$THEME_GREEN_BRIGHT'
let s:amber_bright  = '$THEME_AMBER_BRIGHT'
let s:purple_bright = '$THEME_PURPLE_BRIGHT'
let s:magenta_bright= '$THEME_MAGENTA_BRIGHT'
let s:cyan_bright   = '$THEME_CYAN_BRIGHT'

let s:diff_add    = '$THEME_DIFF_ADD'
let s:diff_change = '$THEME_DIFF_CHANGE'
let s:diff_delete = '$THEME_DIFF_DELETE'
let s:diff_text   = '$THEME_DIFF_TEXT'

EOF

# Map THEME_BORDER_STYLE to Vim borderchars:
#   "rounded" -> ╭╮╯╰  |  "sharp" -> ┌┐┘└
if [[ "$THEME_BORDER_STYLE" == "rounded" ]]; then
  VIM_CORNERS="'╭','╮','╯','╰'"
else
  VIM_CORNERS="'┌','┐','┘','└'"
fi
cat >> "$VIM_OUT" << EOF

" --- Border chars — set from THEME_BORDER_STYLE in colors.sh ---
let g:glitchberry_borderchars = ['─','│','─','│',${VIM_CORNERS}]
EOF

# Write the helper function and highlight definitions (no expansion)
cat >> "$VIM_OUT" << 'VIMEOF'
" --- Export palette for vimrc to reference ---
let g:glitchberry = {'bg': s:bg, 'bg_alt': s:bg_alt, 'sidebar': s:sidebar, 'app': s:app, 'cursorline': s:cursorline, 'selection': s:selection, 'search': s:search, 'fg': s:fg, 'fg_bright': s:fg_bright, 'fg_func': s:fg_func, 'muted': s:muted, 'comment': s:comment, 'border': s:border, 'subtle': s:subtle, 'red': s:red, 'green': s:green, 'amber': s:amber, 'purple': s:purple, 'magenta': s:magenta, 'cyan': s:cyan}

" --- Helper ---
function! s:hi(group, fg, bg, ...) abort
  let l:gui = a:0 >= 1 ? a:1 : 'NONE'
  let l:sp  = a:0 >= 2 ? a:2 : ''
  let l:cmd = 'hi ' . a:group
  let l:cmd .= ' guifg=' . (a:fg ==# '' ? 'NONE' : a:fg)
  let l:cmd .= ' guibg=' . (a:bg ==# '' ? 'NONE' : a:bg)
  let l:cmd .= ' gui='   . l:gui
  if l:sp !=# ''
    let l:cmd .= ' guisp=' . l:sp
  endif
  execute l:cmd
endfunction

" --- Editor ---
call s:hi('Normal',       s:fg,      s:bg)
call s:hi('NormalFloat',  s:fg,      s:sidebar)
call s:hi('FloatBorder',  s:border,  s:sidebar)
call s:hi('Cursor',       s:bg_alt,  s:amber)
call s:hi('lCursor',      s:bg_alt,  s:amber)
call s:hi('CursorIM',     s:bg_alt,  s:amber)
call s:hi('CursorLine',   '',        s:cursorline)
call s:hi('CursorColumn', '',        s:cursorline)
call s:hi('ColorColumn',  '',        s:cursorline)
call s:hi('LineNr',       s:subtle,  '')
call s:hi('CursorLineNr', s:amber,   '')
call s:hi('SignColumn',   s:border,  '')
call s:hi('VertSplit',    s:border,  '')
call s:hi('EndOfBuffer',  s:bg_alt,  '')

" --- Syntax ---
call s:hi('Comment',    s:comment, '', 'italic')
call s:hi('Constant',   s:green,   '')
call s:hi('String',     s:red,     '')
call s:hi('Number',     s:green,   '')
call s:hi('Identifier', s:fg,      '')
call s:hi('Function',   s:fg_func, '')
call s:hi('Statement',  s:purple,  '')
call s:hi('Operator',   s:muted,   '')
call s:hi('PreProc',    s:amber,   '')
call s:hi('Type',       s:cyan,    '')
call s:hi('Special',    s:amber,   '')
call s:hi('Delimiter',  s:muted,   '')
call s:hi('SpecialComment', s:comment, '', 'bold,italic')
call s:hi('Debug',      s:red,     '')
call s:hi('Underlined', s:cyan,    '', 'underline')
call s:hi('Ignore',     s:border,  '')
call s:hi('Error',      s:red,     s:diff_delete)
call s:hi('Todo',       s:amber,   '', 'bold')

hi link Character     String
hi link Boolean       Number
hi link Float         Number
hi link Conditional   Statement
hi link Repeat        Statement
hi link Label         Statement
hi link Keyword       Statement
hi link Exception     Statement
hi link Include       PreProc
hi link Define        PreProc
hi link Macro         PreProc
hi link PreCondit     PreProc
hi link StorageClass  Type
hi link Structure     Type
hi link Typedef       Type
hi link SpecialChar   Special
hi link Tag           Special

" --- Diff ---
call s:hi('DiffAdd',    s:green, s:diff_add)
call s:hi('DiffChange', s:amber, s:diff_change)
call s:hi('DiffDelete', s:red,   s:diff_delete)
call s:hi('DiffText',   s:amber, s:diff_text, 'bold')

" --- UI elements ---
call s:hi('Pmenu',      s:fg,     s:sidebar)
call s:hi('PmenuSel',   s:bg_alt, s:cyan)
call s:hi('PmenuSbar',  '',       s:border)
call s:hi('PmenuThumb', '',       s:comment)

call s:hi('TabLine',     s:muted, s:app)
call s:hi('TabLineFill', '',      s:app)
call s:hi('TabLineSel',  s:fg,    s:bg, 'bold')

call s:hi('StatusLine',   s:fg,      s:app)
call s:hi('StatusLineNC', s:comment, s:app)
hi link StatusLineTerm   StatusLine
hi link StatusLineTermNC StatusLineNC

call s:hi('Visual',    '', s:selection)
call s:hi('VisualNOS', '', s:selection)

call s:hi('Search',    s:bg_alt, s:amber)
call s:hi('IncSearch', s:bg_alt, s:cyan)
call s:hi('CurSearch', s:bg_alt, s:purple)

call s:hi('QuickFixLine', '', s:selection, 'bold')
call s:hi('MatchParen', s:amber, s:border, 'bold')

call s:hi('Folded',     s:comment, s:sidebar)
call s:hi('FoldColumn', s:border,  '')

call s:hi('SpellBad',   '', '', 'undercurl', s:red)
call s:hi('SpellCap',   '', '', 'undercurl', s:purple)
call s:hi('SpellLocal',  '', '', 'undercurl', s:cyan)
call s:hi('SpellRare',  '', '', 'undercurl', s:amber)

call s:hi('Directory',  s:cyan,    '')
call s:hi('Title',      s:purple,  '', 'bold')
call s:hi('MoreMsg',    s:green,   '')
call s:hi('Question',   s:green,   '')
call s:hi('WarningMsg', s:amber,   '')
call s:hi('ErrorMsg',   s:red,     s:bg)
call s:hi('ModeMsg',    s:fg_func, '', 'bold')

call s:hi('WildMenu',   s:bg_alt,  s:purple)
call s:hi('NonText',    s:border,  '')
call s:hi('SpecialKey', s:border,  '')
call s:hi('Conceal',    s:comment, '')
call s:hi('MsgArea',    s:muted,   '')

" --- Terminal colors for :terminal ---
let g:terminal_ansi_colors = [s:border, s:red, s:green, s:amber, s:purple, s:magenta, s:cyan, s:fg, s:comment, s:red_bright, s:green_bright, s:amber_bright, s:purple_bright, s:magenta_bright, s:cyan_bright, s:fg_bright]
VIMEOF
echo "  -> $VIM_OUT"

# ---------- tmux ----------
# Map THEME_BORDER_STYLE to tmux popup-border-lines value:
#   "rounded" -> "rounded" (╭╮╯╰)  |  "sharp" -> "single" (┌┐┘└)
if [[ "$THEME_BORDER_STYLE" == "rounded" ]]; then
  TMUX_BORDER_LINES="rounded"
else
  TMUX_BORDER_LINES="single"
fi

cat > "$TMUX_OUT" << EOF
# Glitchberry — tmux theme  [generated by ~/.config/theme/generate.sh]

# status bar
set -g status-style "bg=default,fg=$THEME_COMMENT"
set -g message-style "bg=$THEME_CURSORLINE,fg=$THEME_FG"
set -g mode-style "bg=$THEME_SELECTION,fg=$THEME_FG"

# pane borders
set -g pane-border-style "fg=$THEME_BORDER"
set -g pane-active-border-style "fg=$THEME_BORDER"

# popups — border-lines set from THEME_BORDER_STYLE in colors.sh
set -g popup-style "fg=$THEME_FG,bg=$THEME_BG"
set -g popup-border-style "fg=$THEME_BORDER,bg=$THEME_BG"
set -g popup-border-lines $TMUX_BORDER_LINES

# expose palette as tmux env vars for scripts
set-environment -g THEME_BG "$THEME_BG"
set-environment -g THEME_FG "$THEME_FG"
set-environment -g THEME_FG_BRIGHT "$THEME_FG_BRIGHT"
set-environment -g THEME_MUTED "$THEME_MUTED"
set-environment -g THEME_COMMENT "$THEME_COMMENT"
set-environment -g THEME_BORDER "$THEME_BORDER"
set-environment -g THEME_SUBTLE "$THEME_SUBTLE"
set-environment -g THEME_CURSORLINE "$THEME_CURSORLINE"
set-environment -g THEME_SELECTION "$THEME_SELECTION"
set-environment -g THEME_AMBER "$THEME_AMBER"
set-environment -g THEME_PURPLE "$THEME_PURPLE"
set-environment -g THEME_CYAN "$THEME_CYAN"
set-environment -g THEME_GREEN "$THEME_GREEN"
set-environment -g THEME_RED "$THEME_RED"
set-environment -g THEME_SESSION_ACCENT "$THEME_SESSION_ACCENT"
set-environment -g THEME_WINDOW_ACCENT "$THEME_WINDOW_ACCENT"
EOF
echo "  -> $TMUX_OUT"

echo "Done. Reload each tool to apply."
